server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

logging:
  level:
    org.springframework.security: trace

app:
  security:
    endpoints:
      white-list: /api-key,/actuator,/swagger,/api-docs

management:
  endpoint:
    health:
      show-details: ALWAYS

springdoc:
  api-docs:
    path: /api-docs
